namespace NuklearC.Native.Types
{
    public enum nk_command_type
    {
        NK_COMMAND_NOP,
        NK_COMMAND_SCISSOR,
        NK_COMMAND_LINE,
        NK_COMMAND_CURVE,
        NK_COMMAND_RECT,
        NK_COMMAND_RECT_FILLED,
        NK_COMMAND_RECT_MULTI_COLOR,
        NK_COMMAND_CIRCLE,
        NK_COMMAND_CIRCLE_FILLED,
        NK_COMMAND_ARC,
        NK_COMMAND_ARC_FILLED,
        NK_COMMAND_TRIANGLE,
        NK_COMMAND_TRIANGLE_FILLED,
        NK_COMMAND_POLYGON,
        NK_COMMAND_POLYGON_FILLED,
        NK_COMMAND_POLYLINE,
        NK_COMMAND_TEXT,
        NK_COMMAND_IMAGE,
        NK_COMMAND_CUSTOM
    }
}